# Generated by Django 4.1.6 on 2023-02-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Specialcar',
                'db_table': 'car',
            },
        ),
    ]
