# Generated by Django 4.1.6 on 2023-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bike_name", models.CharField(max_length=100)),
                ("bike_model", models.CharField(max_length=100)),
                ("bike_color", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Bike List",
                "db_table": "bike",
            },
        ),
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "Special Car"},
        ),
    ]
