# Generated by Django 4.1.6 on 2023-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0002_bike_alter_car_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotorBike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motor_bike_name", models.CharField(max_length=100)),
                ("motor_bike_model", models.CharField(max_length=100)),
                ("motor_bike_color", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Motor Bike List",
                "db_table": "motor bike",
            },
        ),
    ]
