# Generated by Django 4.1.6 on 2023-02-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0003_motorbike"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("content", models.TextField(blank=True)),
            ],
        ),
    ]
